# Pyhton's NumPy Crush Course

## NumPy 

NumPy is a Linear Algebra Library for Python, it is so important for Data Science.

In [1]:
import numpy as np

Some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. 

**Numpy Arrays**


In [2]:
#Vectors are strictly one dimentional arrays
myList = [1,2,3]
myList

[1, 2, 3]

In [3]:
#creating numpy array
np.array(myList)

array([1, 2, 3])

In [4]:
# matrices are usually 2-dimantional arrays 
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [15]:
np.random.rand(2)

array([0.90863859, 0.24920658])

In [16]:
np.random.rand(5,5)

array([[0.63048959, 0.37398919, 0.82693031, 0.3473097 , 0.25152803],
       [0.61538149, 0.64569173, 0.21530274, 0.0766611 , 0.31503103],
       [0.97428843, 0.9896546 , 0.82876217, 0.91425768, 0.2083563 ],
       [0.13227581, 0.614322  , 0.99203399, 0.7172097 , 0.02299329],
       [0.53898181, 0.59255247, 0.25156235, 0.01074451, 0.86945925]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [17]:
np.random.randn(2)

array([0.46688519, 1.23692002])

In [18]:
np.random.randn(5,5)

array([[ 0.26240034,  1.81591854,  0.66191296, -1.59424925, -0.22490383],
       [ 0.54755376, -1.577076  ,  2.30109911,  0.0326021 ,  2.63565105],
       [-0.83930177, -1.06134249,  0.61668584, -0.30276862,  2.65167209],
       [-2.18190615, -1.22827101, -0.34313654, -1.05307009,  0.1808771 ],
       [-0.77670914,  0.19752958,  0.14668407, -0.15475895, -0.63494574]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [19]:
np.random.randint(1,100)

22

In [20]:
np.random.randint(1,100,10)

array([19, 90, 64, 19, 50,  2, 82, 54, 43, 99])

## Array Attributes and Methods

some useful attributes and methods or an array:

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([37, 25, 35, 47, 45, 21, 13, 34, 27, 26])

## Reshape
Returns an array containing the same data with a new shape.

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [25]:
ranarr

array([37, 25, 35, 47, 45, 21, 13, 34, 27, 26])

In [26]:
ranarr.max()

47

In [27]:
ranarr.argmax()

3

In [28]:
ranarr.min()

13

In [29]:
ranarr.argmin()

6

## Shape

Shape is an attribute that arrays have (not a method):

In [30]:
# Vector
arr.shape

(25,)

In [31]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [35]:
arr.dtype

dtype('int64')

# NumPy Indexing and Selection

** Get a value at an index **
** Get values in a range **
** Setting a value with index range (Broadcasting) **
**  **

In [40]:
#array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
#Get a value at an index
arr[9]

9

In [43]:
#Get values in a range
arr[2:9] # notice 2 inclued but 9 not 

array([2, 3, 4, 5, 6, 7, 8])

In [46]:
# Setting a value with index range (Broadcasting)
arr[4:7] = 100
arr

array([  0,   1,   2,   3, 100, 100, 100,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

# Indexing a 2D array (matrices)

In [48]:
arr_2d = np.array(([5,12,15],[21,25,39],[40,45,50]))
arr_2d

array([[ 5, 12, 15],
       [21, 25, 39],
       [40, 45, 50]])

In [51]:
#Indexing row
arr_2d[1]

array([21, 25, 39])

In [52]:
# Getting individual element value
arr_2d[1,0]

21

In [53]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[12, 15],
       [25, 39]])

# NumPy Operations

In [54]:
arr

array([  0,   1,   2,   3, 100, 100, 100,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [55]:
arr + arr

array([  0,   2,   4,   6, 200, 200, 200,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48])

In [56]:
arr**3

array([      0,       1,       8,      27, 1000000, 1000000, 1000000,
           343,     512,     729,    1000,    1331,    1728,    2197,
          2744,    3375,    4096,    4913,    5832,    6859,    8000,
          9261,   10648,   12167,   13824])

**Built-in operations**

In [57]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081, 10.        ,
       10.        , 10.        ,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949])

In [58]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10])

In [59]:
np.log(arr)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 4.60517019,
       4.60517019, 4.60517019, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])